module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#0075d5',
        surface: '#f9f9f9',
        'surface-container-low': '#f3f3f3',
        'outline-variant': '#c0c7d6',
        'tertiary-fixed': '#ffdbc7',
        'on-primary-fixed': '#001c3a',
        'tertiary-fixed-dim': '#ffb688',
        'on-secondary': '#ffffff',
        secondary: '#266d00',
        'on-secondary-fixed': '#062100',
        info: '#1890ff',
        'inverse-primary': '#a5c8ff',
        'on-background': '#1a1c1c',
        'on-secondary-container': '#287100',
        'surface-container-high': '#e8e8e8',
        tertiary: '#934600',
        'on-surface': '#1a1c1c',
        'error-container': '#ffdad6',
        'primary-fixed': '#d4e3ff',
        'surface-container-lowest': '#ffffff',
        success: '#52c41a',
        warning: '#faad14',
        'text-secondary': '#00000073',
        'secondary-fixed': '#88fd54',
        outline: '#707785',
        'on-primary-fixed-variant': '#004785',
        'primary-fixed-dim': '#a5c8ff',
        'inverse-surface': '#2f3131',
        background: '#f9f9f9',
        'on-surface-variant': '#404753',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e2e2e2',
        error: '#ff4d4f',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container': '#eeeeee',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b95a00',
        'on-tertiary-fixed-variant': '#733600',
        'on-tertiary-container': '#fffbff',
        'text-main': '#000000d9',
        'inverse-on-surface': '#f1f1f1',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#005fae',
        'border-base': '#d9d9d9',
        'surface-dim': '#dadada',
        'on-primary-container': '#fefcff',
        'surface-bright': '#f9f9f9',
        'secondary-container': '#85fa51',
        'on-tertiary-fixed': '#311300',
        'on-secondary-fixed-variant': '#1a5200',
        'secondary-fixed-dim': '#6de039',
        primary: '#005daa',
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '4px',
        xl: '4px',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        sm: '8px',
        xs: '4px',
        lg: '24px',
        'margin-desktop': '32px',
        xl: '32px',
        'margin-mobile': '16px',
        md: '16px',
        '2xl': '48px',
        '3xl': '64px',
      },
      fontFamily: {
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
        'body-sm': ['Inter'],
        h2: ['Inter'],
        h3: ['Inter'],
        'body-md': ['Inter'],
        h1: ['Inter'],
        'body-lg': ['Inter'],
        h4: ['Inter'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '20px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '22px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '20px', fontWeight: '400' }],
        h2: ['30px', { lineHeight: '38px', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        h1: ['38px', { lineHeight: '46px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        h4: ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};